version: 2

sources: # One source = one database & one schema, but can have multiple tables
  - name: raw # arbitrary name for the source
    description: "Raw data from the NYC taxi trips" # optional description of the source
    database: kestra-sandbox-486905 # this is the GCP project id. If omitted, dbt will use the project specified in project.yml (if local) or dbt cloud (if using that)
    schema: zoomcamp # this is the dataset in the bigquery database
    tables: # tables to be used in the project. Doesn't have to be all the tables in the dataset.
      - name: green_tripdata
      - name: yellow_tripdata

